
###
GET http://127.0.0.1:8000/api/aws-sms-test HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://127.0.0.1:8000/api/crone-job-test HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|5vthuk5GMeqkj8izK08MDiQFLObokSS6vyI8AR8N

###

GET http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "admin@demo.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|87rzt4JlT9bMRdiTcpUGKLWZGfxQa6IgZloxf54U

{
    "name": "Abduljawad Ibraheem Narumah",
    "phone_number": "07066352444",
    "email": "abdouljawadibrahim@gmail.com",
    "password": "password",
    "password_confirmation": "password",
    "gender": "Male",
    "dob": "2022-06-21",
    "group_id": 1
}

###
GET http://127.0.0.1:8000/api/birthdays-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
GET http://127.0.0.1:8000/api/users-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
GET http://127.0.0.1:8000/api/admin-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0gw5zCPn1ISN3SSg66lHoWULSvnwp0B1SK4GQBCq

###
GET http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
DELETE http://127.0.0.1:8000/api/admin/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
PUT http://127.0.0.1:8000/api/admin/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|ozHf9dkz5yrGcy5LbL0SisA9lTfBMXFvVXwgsMSw

{
    "name": "ABDULJAWAD IBRAHIM Narumah",
    "email": "jawadNarumahs@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-23",
    "group_id": 4
}

###
GET http://127.0.0.1:8000/api/birthdays HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
GET http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|p1Cqhdwd50t9bC92vhBdHkjdaGnOVyLLvL8WsuLV

###
GET http://127.0.0.1:8000/api/user-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0gw5zCPn1ISN3SSg66lHoWULSvnwp0B1SK4GQBCq

###
GET http://127.0.0.1:8000/api/birthday HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0gw5zCPn1ISN3SSg66lHoWULSvnwp0B1SK4GQBCq

###
GET http://127.0.0.1:8000/api/birthday-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0gw5zCPn1ISN3SSg66lHoWULSvnwp0B1SK4GQBCq

###
POST http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|GTw3vQysVgARlexEWN4v9AeUZPQgdyjCMkJXZKnc

{
    "name": "Imrana A. Bala",
    "phone_number": "07066352444",
    "email": "asddda@gmail.com",
    "gender": "Male",
    "dob": "2022-06-20"
}

###
PUT http://127.0.0.1:8000/api/user/4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|GTw3vQysVgARlexEWN4v9AeUZPQgdyjCMkJXZKnc

{
    "name": "ABDULJAWAD IBRAHIM",
    "email": "jawads12rumahh@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-01"

}

###
GET http://127.0.0.1:8000/api/user/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|GTw3vQysVgARlexEWN4v9AeUZPQgdyjCMkJXZKnc

###
DELETE http://127.0.0.1:8000/api/user/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|GTw3vQysVgARlexEWN4v9AeUZPQgdyjCMkJXZKnc

###
GET http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
GET http://127.0.0.1:8000/api/group-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
POST http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

{
    "group_name": "Jay Concepts ",
    "admin_id": 3
}

###
GET http://127.0.0.1:8000/api/group/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
PUT http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

{
    "group_name": "JayConcepts"
}

###
DELETE http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
POST http://127.0.0.1:8000/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj
###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
ontent-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

{
    "group_id": 1,
    "profile_id": 7,
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/add-member HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|gXrxRfYxEZQd8AwP2Lr2CZI8w792O7VSkCV4w04P

{
    "email": "daomenico56@example.com",
    "group_id": 1
}

###
GET http://127.0.0.1:8000/api/admin-group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj
###
GET http://127.0.0.1:8000/api/admin-profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

###
GET http://127.0.0.1:8000/api/search HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|9bF9jJH63PsKGjXKihLBvrOQlqD2imxkAtTluJBj

{
    "search": "jawad"
}
