// group: index,

GET http://127.0.0.1:8000/api/aws-sms-test HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://127.0.0.1:8000/api/crone-job-test HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|qdB5m8Z8UYHya1IY8Y4iiagmzqF9ddgKw4BITX4w

###

GET http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|SmY65fjhBRIhdGCKAMUden5hAIA6XYGhgzmWyDis

###
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "admin@demo.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|SmY65fjhBRIhdGCKAMUden5hAIA6XYGhgzmWyDis

{
    "name": "Abduljawad Ibraheem Narumah",
    "phone_number": "07066352444",
    "email": "jayNarumah@gmail.com",
    "password": "password",
    "password_confirmation": "password",
    "gender": "Male",
    "dob": "2022-06-21",
    "group_id": 1
}

###
GET http://127.0.0.1:8000/api/birthdays-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Va9ogQZK0in95C43tmkTxytSUlLkU2LLGYXuEg2V

###
GET http://127.0.0.1:8000/api/users-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Va9ogQZK0in95C43tmkTxytSUlLkU2LLGYXuEg2V

###
GET http://127.0.0.1:8000/api/admin-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Va9ogQZK0in95C43tmkTxytSUlLkU2LLGYXuEg2V

###
GET http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|SmY65fjhBRIhdGCKAMUden5hAIA6XYGhgzmWyDis

###
DELETE http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Va9ogQZK0in95C43tmkTxytSUlLkU2LLGYXuEg2V

###
POST http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|SmY65fjhBRIhdGCKAMUden5hAIA6XYGhgzmWyDis

{
    "name": "ABDULJAWAD IBRAHIM Narumah",
    "email": "jawadNarumah@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-23",
    "group_id": 4
}

###
GET http://127.0.0.1:8000/api/birthdays HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|Va9ogQZK0in95C43tmkTxytSUlLkU2LLGYXuEg2V

###
GET http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
GET http://127.0.0.1:8000/api/user-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
GET http://127.0.0.1:8000/api/birthday HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
GET http://127.0.0.1:8000/api/birthday-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
POST http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

{
    "name": "Imrana A. Bala",
    "phone_number": "07066352444",
    "email": "asddsddsaaaassadadaaasaaaaaasaaa@gmail.com",
    "gender": "Male",
    "dob": "2022-06-20"
}

###
POST http://127.0.0.1:8000/api/user/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

{
    "name": "ABDULJAWAD IBRAHIM",
    "email": "jawadrumah@gmail.com",
    "phone_number": "07035460599",
    "gender": "Female",
    "dob": "2022-06-01"

}

###
GET http://127.0.0.1:8000/api/user/4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
DELETE http://127.0.0.1:8000/api/user/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|tAXDgmdDLFq7cpGD7lDWVX73BsgzQL5kMloMBr0J

###
GET http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0P4q2CvJpJcTfnPVTMmlLQXrpn9SyIEljoXDDqHe

###
GET http://127.0.0.1:8000/api/group-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|5QdpPEHxofyjXZbbx8xvAlSdYhFrvidcuter2Q2c

###
POST http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|SPC87PNaLSMGbSau8XxC3IoWiOHzHZRwyIF5ubok

{
    "group_name": "Jay Concept ",
    "admin_id": 3
}

###
GET http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cI2JgBCAfGbCmqmTjDwO6QEfvwXmHia5JXzBfsCk

###
POST http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|MjEtMeJQ2x9LSNmq5B5fPalmfR8wB7SPRQwqu2ld

{
    "group_name": "JayConcepts"
}

###
DELETE http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|5QdpPEHxofyjXZbbx8xvAlSdYhFrvidcuter2Q2c

###
POST http://127.0.0.1:8000/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
ontent-Type: application/json
Accept: application/json
Authorization: Bearer 1|NkJUCedo9cZNOaytD4I8ta9K4Yg9ovCNcuODRn0W

{
    "group_id": 1,
    "profile_id": 1,
    "password": "password"
}

###

POST http://127.0.0.1:8000/api/add-member HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|NkJUCedo9cZNOaytD4I8ta9K4Yg9ovCNcuODRn0W

{
    "email": "jaylan34@example.net",
    "group_id": 1
}

###
GET http://127.0.0.1:8000/api/admin-group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|hX1cqW2BIEUiZSo5erleWDhxOTfq4ltvN93hJuSv


