
###
GET http://127.0.0.1:8000/api/aws-sms-test HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://127.0.0.1:8000/api/crone-job-test HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|5vthuk5GMeqkj8izK08MDiQFLObokSS6vyI8AR8N

###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|rfu4rHqDmcYjZKXuG0uIrsYqTdW6m4a56QlLUNJy

{
    "user_id": 2,
    "group_id": 3
}
####
GET http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 12|lBHzt4GdcZQWtEJUwOiyNjl9XaYbqlAk2B61C1TJ

###
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "super@demo.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

{
    "name": "Abduljawad Ibraheem Narumah",
    "phone_number": "07066352444",
    "email": "jawad@demo.com",
    "password": "password",
    "password_confirmation": "password",
    "gender": "Male",
    "dob": "2022-06-21"
    //"group_id": 1
}

###
GET http://127.0.0.1:8000/api/birthdays-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
GET http://127.0.0.1:8000/api/users-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
GET http://127.0.0.1:8000/api/admin-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
GET http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
DELETE http://127.0.0.1:8000/api/admin/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
PUT http://127.0.0.1:8000/api/admin/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

{
    "name": "ABDULJAWAD IBRAHIM Narumah",
    "email": "jawadNarumahs@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-23",
    "group_id": 2
}

###
GET http://127.0.0.1:8000/api/birthdays HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M
###
GET http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
GET http://127.0.0.1:8000/api/group-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

###
POST http://127.0.0.1:8000/api/group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

{
    "group_name": "Jay ",
    "admin_id": 3
}

###
GET http://127.0.0.1:8000/api/group/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M
###
PUT http://127.0.0.1:8000/api/group/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M

{
    "group_name": "JayConcepts"
}
###
DELETE http://127.0.0.1:8000/api/group/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M


###
GET http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

###
GET http://127.0.0.1:8000/api/user-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

###
GET http://127.0.0.1:8000/api/birthday HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

###
GET http://127.0.0.1:8000/api/birthday-count HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

###
POST http://127.0.0.1:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

{
    "name": "Imrana A. Bala",
    "phone_number": "07066352444",
    "email": "asdddaa@gmail.com",
    "gender": "Male",
    "dob": "2022-06-20"
}

###
PUT http://127.0.0.1:8000/api/user/4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

{
    "name": "ABDULJAWAD IBRAHIM",
    "email": "jawads12rumahh@gmail.com",
    "phone_number": "07035460599",
    "gender": "Male",
    "dob": "2022-06-01"

}

###
GET http://127.0.0.1:8000/api/user/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f

###
DELETE http://127.0.0.1:8000/api/user/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f


###
POST http://127.0.0.1:8000/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|PxNWZqDHtuQboPsQwlQOmEEt1hDDnHPX3hdJxB3M
###
POST http://127.0.0.1:8000/api/create-admin HTTP/1.1
ontent-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "group_id": 1,
    "profile_id": 7,
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/add-member HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "email": "theresa.romaguera@example.com",
    "group_id": 3
}

###
GET http://127.0.0.1:8000/api/admin-group HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|BggJQ6Xn2mnSCJczeqwR6cyO9PEaFpQ0oBdRCv3f
###
GET http://127.0.0.1:8000/api/admin-profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

###
GET http://127.0.0.1:8000/api/search HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|pGvfaVnFzpRBrzG0iwApoWxe2ryq9GPJOyWVl0rg

{
    "search": "jawad"
}
